### ISSUE TITLE
F-Droid merge request opened

### ISSUE THREAD

**Issue by fi3te** [fi3te/NotificationCron#1]
https://gitlab.com/fdroid/fdroiddata/merge_requests/5147

**Comment by IzzySoft** [comment]
Was published yesterday, so this issue is solved I guess. Though it would be nice if there was a more detailed description. When reading the existing one, my first thought was "I could simply create a reoccuring calendar event instead". There must be more to it :wink:

**Comment by TPS** [comment]
@IzzySoft I'm kinda hoping this will expand from just scheduled notifications, as well, as this seems precisely covered by [Repeat Me (Schedule custom, interval based reminders)](https://f-droid.org/app/com.samarthdesai.repeatme), as well as any more complex calendar app.

@fi3te Maybe it can eventually include scheduled intents or other actions, thereby earning the [namesake](https://en.m.wikipedia.org/wiki/Cron)?  I do enjoy the very few permissions required, & hope the interface remains simpler than [crond (Schedules scripts)](https://f-droid.org/app/it.faerb.crond).

**Comment by fi3te** [comment]
@IzzySoft I've updated the description and added a README file with screenshots of the app. Users should now know if they want to use such an application 😄 

@TPS For time reasons, no major updates are currently planned 😞

**Comment by IzzySoft** [comment]
@fi3te Thanks! Yes, now it is much clearer. Can't do that "every 10min" entry with my calendar without "funny side-effects" :rofl:
