### ISSUE TITLE
Multiple notifications are not grouped together

### ISSUE THREAD

**Issue by user8446** [fi3te/NotificationCron#10]
Normally, all notifications from a single app are grouped together. This works as expected with other apps on my device. However, with notification cron they are not grouped:

![Screenshot_20200122-213041](https://user-images.githubusercontent.com/18019245/72952302-6beb6d80-3d5f-11ea-9edc-309aba18fad3.png)

Alternatively, you could have the app behavior: if there is already a repeated notification present that was not dismissed, then don't display another duplicate one. 

Either would keep the notification shade from filling up with the same multiple notifications

Android 8.1 / Moto G5 Plus
App version 1.0.2

**Comment by fi3te** [comment]
Hi user8446,

the app already uses a so-called notification channel. Notifications are apparently grouped only when the number of notifications is 4 or higher. If there is a configuration option for it, I will change it.

Best regards,
Fiete

**Comment by user8446** [comment]
Hi Fiete,

I did a little digging and it looks like you just have to set a group:

https://developer.android.com/training/notify-user/group

Unfortunately, I'm not an Android dev to help further

**Comment by fi3te** [comment]
Hi user8446,

I solved the problem with your link. The troubleshooting will be part of the next (but one) update.

Best regards,
Fiete

**Comment by user8446** [comment]
@fi3te 
Thank you Fiete for the development!
