### ISSUE TITLE
v1.1.1 notification groups

### ISSUE THREAD

**Issue by user8446** [fi3te/NotificationCron#12]
Hello,
After the update to 1.1.1 I tested and notifications are still separate until there are 4 of them. Once it hits 4 though, they will all stay grouped even if it's less than 4.

**Comment by fi3te** [comment]
Hi user8446,
are you sure you have installed version 1.1.1?
I installed the app again directly from F-Droid. The grouping of notifications works for me already with two notifications.
Best regards,
Fiete

**Comment by user8446** [comment]
Hi I just looked and the latest release version even after a refresh on FDroid is 1.1.0 not 1.1.1?

**Comment by fi3te** [comment]
For me, the process is also somewhat opaque.
