### ISSUE TITLE
[Feature Request] On notification click

### ISSUE THREAD

**Issue by hXtreme** [fi3te/NotificationCron#16]
**Description:**
Add the option to assign an action when a notification is clicked.

**Why:**
This would allow for a much more integrated use case rather than just setting reminders.

**How:**
Many applications use [Deep Links](https://developer.android.com/training/app-links/deep-linking), or [app links](https://developer.android.com/training/app-links) to open url/uri in app.
NotificationCron can make use of the apps that provide this feature by letting the user setup a url that would be opened when the notification is clicked, triggering the app.

_Example use case:_
Say I want to follow a particular post on Reddit every 6 hours I would set-up the app to the following:
```
Expression: 0 0 */6 * * ?
Title: Check Reddit post
Text: Bossfight: Mei the soul eater.
onClick: https://www.reddit.com/r/Bossfight/comments/gfz2kb
```

So when the notification pops up I can click on the notification after which my Reddit app (who has reddit.com links registered) will take over and open the post.

---

Please let me know if you would like any clarifications.

**Comment by hXtreme** [comment]
@fi3te let me know if you are interested in this feature and I'll try implementing it.

**Comment by fi3te** [comment]
Hi hXtreme,

I think that this feature fits into the scope of the app.

Best regards,
Fiete

**Comment by hXtreme** [comment]
Awesome!

**Comment by hXtreme** [comment]
@fi3te to implement this I need to make a change from Triple to a new data class (called either `Quadruple` or `NotificationCronInput`)
https://github.com/fi3te/NotificationCron/blob/275e3e15e87a40f50a3860414bd8cde848c5cfec/app/src/main/java/com/github/fi3te/notificationcron/ui/NotificationCronDialog.kt#L84

Now my question is, where should I create this class and what should I name it.

PS: I need the new class because getInput would additionally have to return `notificationActionInput`.

**Comment by fi3te** [comment]
Please excuse my late reply!

I think you could add the new class in the package
com.github.fi3te.notificationcron.data.local

**Comment by hXtreme** [comment]
Expect a pr in a few hours.
