### ISSUE TITLE
[Feature Request] Custom notification sound and export CRON

### ISSUE THREAD

**Issue by aintyourcat** [fi3te/NotificationCron#17]
Hello, thanks for the app, i really like it, but there're 2 features that i guess will make this app even better:
1) Custom notification for each CRON;
2) Export the existing CRON(s) to a file and import the CRON file that have exported before.

**Comment by hXtreme** [comment]
I recommend that you make two separate issues for each of them respectively.

You should also be a bit more descriptive about the Import Export feature, what is the underlying problem you're trying to solve? Do you plan to export/import to/from another app or your PC or is it just for backup purpose when transferring phones. Knowing this would probably lead to a better design for the solution.

**Comment by aintyourcat** [comment]
I'm sorry for that, I'm new to GitHub, so i need to delete this?

The reason why i think the import export feature will be useful is when there's people like me that uses custom ROM on their phone. Sometimes when there's an update, it needed to be flashed cleanly, so if if i don't have the  backup of my CRONs, I'll lose them because clean flash will format the phone system. Therefore, it will be useful if i can make a backup of the current CRONs. I know that i can make a backup by copying the CRONs to a file manually, but i believe that it will be much easier if i can make it just by single tap.

**Comment by fi3te** [comment]
Hi aintyourcat,

please excuse my late reply!

No, you don't have to delete this issue 😄 
An export/import feature is in my opinion a useful improvement.

For the notification sound feature please comment #8 with your suggestions.

Best regards,
Fiete

**Comment by 97997** [comment]
I would really love to be able to import/export for backup purposes since i have tens of configured alarms. Adding that feature would make this app perfect

**Comment by fi3te** [comment]
The import/export feature is part of the release v1.6.0.
