### ISSUE TITLE
Instructions and examples

### ISSUE THREAD

**Issue by hugh-m** [fi3te/NotificationCron#2]
Could you post brief instructions with examples for the Notification Cron expressions. I just can't work them out.

**Comment by dAnjou** [comment]
Same here. I entered a perfectly fine cron expression and tapping Create doesn't do anything.

**Comment by cyko69** [comment]
> Same here. I entered a perfectly fine cron expression and tapping Create doesn't do anything.

Same for me

**Comment by dAnjou** [comment]
Ah, got it as well. Example for "every 5 minutes": `0 0/5 * * * ?`.

The creation dialog should contain some examples that you can directly use because it's also quite cumbersome to enter.

**Comment by shreyasminocha** [comment]
I think the cron field should have more hints.

- Separate fields with labels for eaach component
- Custom keypad (I guess the dialpad keybad should work fine)

**Comment by fi3te** [comment]
I have released a new version with a separate help dialog.

**Comment by fi3te** [comment]
@shreyasminocha @dAnjou I have created a separate issue for the input improvements.
