### ISSUE TITLE
[Question] Next release date

### ISSUE THREAD

**Issue by hXtreme** [fi3te/NotificationCron#22]
Recently there's been a bit of activity on the repo as well as a new github release.
So I was wondering if there is any planned release date on F-droid? Alternatively can you add pre-built apk to the github release, it would make it easier to update the app on my device?

**Comment by vinniec** [comment]
i ask the same because fDroid 1.2.0 doesn't work on my phone. The program does not play any notification even if I use the example in the help to play at every hour. The test sound works.

**Comment by vinniec** [comment]
Thanks for fdroid's update, now your app work for me :)
I want to ask another small thing, is it possible to permit to change the sound of the alarm?
The default sound don't have enough volume for my ears :p

**Comment by hXtreme** [comment]
@vinniec I think you should talk about notification sound on #8.

**Comment by fi3te** [comment]
It always takes a few days until a new version is created in F-Droid for a Git tag. A GitHub action that builds an APK for every tag/release would be helpful 😃
