### ISSUE TITLE
Is having a schedule the app is active on the roadmap?

### ISSUE THREAD

**Issue by user8446** [fi3te/NotificationCron#9]
In other words, say I wanted a cron for a hourly notification but only during the day. Otherwise, it would run 24 hours.
Thank you

**Comment by Filius-Patris** [comment]
You can use cron syntax to express that. Just specify The hours you want and then the 1st minute and the 1st second.

**Comment by fi3te** [comment]
An example would be `0 0 6-22 * * ?`.

**Comment by user8446** [comment]
Got it. I completely forgot you can use a range. Thank you
